### ISSUE TITLE
Room Changes

### ISSUE THREAD

**Issue by MeinKraft** [waidesoper/thevaultCE#80]
- [x] Replace `bedrock` with `vault:vault_bedrock`
- [x] Replace `chests/barrels` with `loot boxes`
- [x] Placeholders for VH2 obelisks
- [x] Mini altars

**Comment by waidesoper** [comment]
I have so far replaced the bedrock in the tunnels an all the main rooms. I'm cautious to do the treasure rooms, because I don't want to break the doors again, also the boss rooms are a bit more complicated. So we can either consider this done at this, or I can keep pushing on.
